package-lock.json
package.json
src/app/app.config.ts

Make Angular run without ZoneJS.
See [Angular without ZoneJS](https://next.angular.dev/guide/experimental/zoneless).

Remove ZoneJS

---

.devcontainer/Dockerfile
.devcontainer/create_cert
.devcontainer/data-portal.yaml
.devcontainer/dev_install
.devcontainer/dev_launcher
.devcontainer/devcontainer.json
.gitignore
README.md
angular.json
data-portal.default.yaml
package.json
pnpm-lock.yaml
proxy.staging.conf.json
run.js
src/index.html
src/styles.scss

This PR improves the `dev_launcher` script to allow switching between "localhost" (MSW) and "staging" (real backend) by just passing the "staging" option on the command line.

Support two different modes of running the dev server

---

src/app/app.component.html

Suggested solution to [keep the footer where it belongs](https://www.freecodecamp.org/news/how-to-keep-your-footer-where-it-belongs-59c6aa05c59c/), using a flexbox layout.

Push footer to the bottom of the visible page

---

src/app/app.config.ts
src/app/app.routes.ts

This is just a minor update to provide page titles in the router.

Adding page titles to the router.

---

src/app/app.config.ts
src/app/auth/features/confirm-totp/confirm-totp.component.ts
src/app/auth/features/register/register.component.ts
src/app/auth/services/auth.service.ts
src/app/metadata/features/dataset-expansion-panel/dataset-expansion-panel.component.ts
src/app/metadata/features/global-summary/global-summary.component.html
src/app/metadata/features/global-summary/global-summary.component.scss
src/app/metadata/features/global-summary/global-summary.component.spec.ts
src/app/metadata/features/global-summary/global-summary.component.ts
src/app/metadata/features/metadata-browser/metadata-browser.component.ts
src/app/metadata/services/metadata.service.ts
src/app/portal/features/home-page/home-page.component.spec.ts
src/app/shared/services/notification.service.spec.ts
src/app/shared/services/notification.service.ts
src/app/shared/ui/custom-snack-bar/custom-snack-bar.component.html
src/app/shared/ui/custom-snack-bar/custom-snack-bar.component.scss
src/app/shared/ui/custom-snack-bar/custom-snack-bar.component.spec.ts
src/app/shared/ui/custom-snack-bar/custom-snack-bar.component.ts
src/styles.scss
tests/home.spec.ts

- add reusable notification service for different types of notifications
- show notifications (mostly error messages) where needed in the existing code
- add tests
- add loading indicators

Add and use notification service

---

src/app/metadata/features/metadata-browser/metadata-browser.component.html
src/app/metadata/features/metadata-browser/metadata-browser.component.spec.ts
src/app/metadata/features/metadata-browser/metadata-browser.component.ts
src/app/metadata/models/facet-filter.ts
src/app/metadata/services/metadataSearch.service.spec.ts
src/app/metadata/services/metadataSearch.service.ts
src/app/metadata/utils/facetActivity.pipe.spec.ts
src/app/metadata/utils/facetActivity.pipe.ts

I first implemented search and then noticed that filter facets were closely related so I included it. 
This contains: 
- Search
- Filter Facets
- Chips
- and some tests

Filtering and Search in the Browse view

---

src/app/metadata/features/metadata-browser/metadata-browser.component.spec.ts
src/app/metadata/features/metadata-browser/metadata-browser.component.ts

Covers search, filter facets, page size and skip.

Route parameters for the browse view

---

src/app/auth/features/setup-totp/setup-totp.component.ts
src/app/portal/features/home-page/home-page.component.html
src/app/work-packages/features/work-package/work-package.component.html
src/app/work-packages/features/work-package/work-package.component.ts
src/app/work-packages/services/work-package.service.ts
src/mocks/data.ts
src/mocks/responses.ts
src/styles.scss

This PR completes the work package creation functionality.

Create work package and display token (GSI-1303)

---

.devcontainer/dev_launcher
.vscode/settings.json
proxy.conf.mjs
src/app/metadata/features/global-summary/global-summary.component.html
src/app/metadata/models/global-summary.ts
src/app/shared/utils/errors.spec.ts
src/app/shared/utils/errors.ts
src/app/work-packages/features/work-package/work-package.component.html
src/app/work-packages/features/work-package/work-package.component.ts
src/mocks/data.ts
src/mocks/responses.ts

- Improve error messages in dev launcher
- Fix issue when global stats do not return detailed stats
- Add helper function for deriving a user friendly error from the backend response
- Improve error handling when work-package creation fails
- This has been tested against staging to make sure the expected error is displayed to the user

Fix work-package token creation issues (GSI-1356)

---

src/app/access-requests/features/access-request-dialog/access-request-dialog.component.html
src/app/access-requests/features/access-request-dialog/access-request-dialog.component.ts
src/app/access-requests/features/dynamic-access-request-button/dynamic-access-request-button.component.html

This PR includes form validation for the Access Request Dialog. It checks the date bounds, email and requires a description. Otherwise, the submit button is disabled.

Add form validation for access request form GSI-1456

---

src/app/access-requests/features/access-request-manager-filter/access-request-manager-filter.component.html
src/app/access-requests/features/access-request-manager-filter/access-request-manager-filter.component.scss
src/app/access-requests/features/access-request-manager-filter/access-request-manager-filter.component.spec.ts
src/app/access-requests/features/access-request-manager-filter/access-request-manager-filter.component.ts
src/app/access-requests/features/access-request-manager/access-request-manager.component.html
src/app/access-requests/features/access-request-manager/access-request-manager.component.spec.ts
src/app/access-requests/features/access-request-manager/access-request-manager.component.ts
src/app/access-requests/models/access-requests.ts
src/app/access-requests/services/access-request.service.ts

Implement the filter component for the access request manager.

Access request manager: Filter (GSI-1359)

---

src/app/access-requests/features/dynamic-access-request-button/dynamic-access-request-button.component.html
src/app/access-requests/features/granted-access-requests-list/granted-access-requests-list.component.html
src/app/access-requests/features/granted-access-requests-list/granted-access-requests-list.component.ts

The account page was still missing the download button that appeared when there was a granted access.

Add download button for granted access

---

src/app/access-requests/features/dynamic-access-request-button/dynamic-access-request-button.component.html
src/app/access-requests/features/dynamic-access-request-button/dynamic-access-request-button.component.scss
src/app/access-requests/features/granted-access-requests-list/granted-access-requests-list.component.html
src/app/access-requests/features/pending-access-requests-list/pending-access-requests-list.component.html
src/app/auth/services/auth.service.ts
src/app/metadata/features/dataset-details/dataset-details.component.html
src/app/metadata/features/dataset-details/dataset-details.component.scss
src/app/metadata/features/dataset-summary/dataset-summary.component.html
src/app/metadata/features/dataset-summary/dataset-summary.component.scss
src/app/metadata/features/metadata-browser/metadata-browser.component.html
src/app/metadata/features/metadata-browser/metadata-browser.component.scss
src/app/metadata/features/search-result/search-result.component.scss
src/app/portal/features/account-button/account-button.component.html
src/app/portal/features/account-button/account-button.component.scss
src/app/portal/features/account/account.component.html
src/app/shared/services/confirmation.service.ts
src/app/shared/utils/date-formats.ts
src/app/verification-addresses/features/new-iva-dialog/new-iva-dialog.component.html
src/app/verification-addresses/features/new-iva-dialog/new-iva-dialog.component.ts
src/app/verification-addresses/features/user-iva-list/user-iva-list.component.html
src/app/verification-addresses/features/user-iva-list/user-iva-list.component.ts
src/app/verification-addresses/features/verification-dialog/verification-dialog.component.html
src/styles.scss
tailwind.config.js

Made some changes to the account page and associated components.
Some prettification of the dataset summary panel, etc.

Polishing of the account page (GSI-1345)

---

src/app/access-requests/features/access-request-dialog/access-request-dialog.component.html
src/app/access-requests/services/access-request.service.ts
src/app/metadata/features/dataset-summary/dataset-summary.component.html
src/app/metadata/features/metadata-browser/metadata-browser.component.html
src/app/metadata/features/metadata-browser/metadata-browser.component.scss
src/app/metadata/features/metadata-browser/metadata-browser.component.ts
src/app/verification-addresses/pipes/iva-state.pipe.spec.ts
src/app/verification-addresses/pipes/iva-type.pipe.spec.ts

Added responsiveness to metadata browser page and associated components.
Some minor corrections to comments for some pipe tests, etc.

Responsive metadata browser (GSI-1431)

---

eslint.config.js
src/app/work-packages/features/work-package/work-package.component.html
tests/access-request-manager.spec.ts
tests/account.spec.ts
tests/browse.spec.ts
tests/fixtures.ts
tests/home.spec.ts
tests/iva-manager.spec.ts
tests/work-pacakge.spec.ts

This PR improves the existing e2e-tests and adds some more tests so that all important pages are covered.

Add more end-to-end testing

---

package.json
src/app/access-requests/features/access-request-dialog/access-request-dialog.component.spec.ts
src/app/access-requests/features/access-request-manager-dialog/access-request-manager-dialog.component.spec.ts
src/app/access-requests/features/access-request-manager-list/access-request-manager-list.component.spec.ts
src/app/access-requests/features/dynamic-access-request-button/dynamic-access-request-button.component.spec.ts
src/app/access-requests/services/access-request.service.ts
src/app/metadata/features/dataset-details/dataset-details.component.html
src/app/metadata/features/dataset-details/dataset-details.component.spec.ts
src/app/metadata/features/dataset-summary/dataset-summary.component.html
src/app/metadata/features/dataset-summary/dataset-summary.component.spec.ts
src/app/metadata/features/search-result-list/search-result-list.component.html
src/app/metadata/features/search-result/search-result.component.html
src/app/metadata/features/search-result/search-result.component.spec.ts
src/app/metadata/features/search-result/search-result.stencil.component.html
src/app/work-packages/features/work-package/work-package.component.spec.ts
src/mocks/data.ts
src/mocks/responses.ts
tests/account.spec.ts
tests/browse.spec.ts
tests/work-pacakge.spec.ts

Fixed length of accession strings to match production
Fixed the way they display
Improved displaying of data not present in DINS
Fixed bottom spacing of buttons in dataset summary

Fixes to accession mock strings and their displaying

---

package.json
pnpm-lock.yaml
src/app/work-packages/features/work-package/work-package.component.html
src/app/work-packages/features/work-package/work-package.component.ts

The download token should be prefixed with the internal work package ID, not with the dataset ID.
This PR also makes sure that the hyphens in the ID (a UUID) do not cause a word wrap.

Add proper ID to download token

---

package.json
src/app/metadata/features/dataset-details/dataset-details.component.html
src/app/metadata/features/dataset-details/dataset-details.component.ts
src/app/metadata/features/metadata-browser/metadata-browser.component.html
src/app/metadata/features/metadata-browser/metadata-browser.component.ts
src/app/metadata/models/dataset-details.ts
src/app/metadata/pipes/facet-activity.pipe.spec.ts
src/app/metadata/pipes/facet-activity.pipe.ts
src/app/metadata/pipes/storage-alias.pipe.ts
src/app/metadata/pipes/validate-doi.pipe.spec.ts
src/app/metadata/pipes/validate-doi.pipe.ts
src/mocks/data.ts
tests/browse.spec.ts

Fixes mismatch of optional parameters in Publication model between th…e data portal and ground truth.
Fixes pagination behaviour when filtering.
Bumps version to 2.0.4.

Hotfix for publications and pagination

---

.devcontainer/data-portal.yaml
data-portal.default.yaml
package.json
src/app/access-requests/features/access-request-dialog/access-request-dialog.component.spec.ts
src/app/access-requests/features/access-request-dialog/access-request-dialog.component.ts
src/app/metadata/features/metadata-browser/metadata-browser.component.html
src/app/metadata/features/metadata-browser/metadata-browser.component.spec.ts
src/app/metadata/features/metadata-browser/metadata-browser.component.ts
src/app/shared/services/config.service.spec.ts
src/app/shared/services/config.service.ts

- Minor clean-up in configuration
- Add config option for max facet options (GSI-1637)
- Improve placeholder for search field (GSI-1638)

Quickfix for search and facets

---

src/app/metadata/features/global-summary/global-summary.component.html
src/app/metadata/features/global-summary/global-summary.component.spec.ts
src/app/metadata/features/global-summary/global-summary.component.ts
tests/home.spec.ts

Also add thousand separator to counts.

Test aggregation in global stats

---

src/app/access-requests/features/access-grant-details/access-grant-manager-details.component.ts
src/app/access-requests/features/access-request-manager-detail/access-request-manager-detail.component.ts
src/app/auth/features/user-manager-detail/user-manager-detail.component.spec.ts
src/app/auth/features/user-manager-detail/user-manager-detail.component.ts
src/app/auth/services/user.service.ts
src/app/metadata/features/dataset-details/dataset-details.component.ts
src/app/shared/services/navigation.service.ts

Instead of just using the back navigation of the platform, views can now provide a fallback if there is no history. In that way, the buttons always perform a navigation and use a sensible default if no history exists.

Smart navigation back implementation

---

src/app/access-requests/features/access-grant-details/access-grant-manager-details.component.html
src/app/access-requests/features/access-grant-manager/access-grant-manager.component.html
src/app/access-requests/features/access-request-manager-detail/access-request-manager-detail.component.html
src/app/access-requests/features/access-request-manager/access-request-manager.component.html
src/app/auth/features/setup-totp/setup-totp.component.html
src/app/auth/features/user-manager-detail/user-manager-detail.component.html
src/app/auth/features/user-manager/user-manager.component.html
src/app/metadata/features/dataset-details/dataset-details.component.html
src/app/metadata/features/dataset-details/dataset-details.component.spec.ts
src/app/metadata/features/metadata-browser/metadata-browser.component.html
src/app/portal/features/account/account.component.html
src/app/portal/features/home-page/home-page.component.html
src/app/portal/features/page-not-found/page-not-found.component.html
src/app/verification-addresses/features/iva-manager/iva-manager.component.html

Also:
Added semantically relevant \<header\> elements for all pages even if not necessary, even for a11y
Added aria-label for 404 page contact form link

Added missing h1 in browse page
