ghga-de/data-portal

- angular.json
- eslint.config.js
- package.json
- pnpm-lock.yaml
- src/app/portal/features/home-page/home-page.component.html
- src/app/portal/features/home-page/home-page.component.ts
- src/main.ts
- src/mocks/data.ts
- src/mocks/handlers.ts
- src/mocks/mockServiceWorker.js
- src/mocks/responses.ts
- src/mocks/setup.ts
This PR adds support for MSW for local testing without backend.
- We are following the same principle as in the legacy app.
- Mock responses must be specified as static data - this avoids intricate re-implementation of the real backend that will deviate from reality anyway.
- The responses are auto-converted to a list of handlers as expected by MSW.
- I have added two demo responses and a demo usage in the home page component that should be removed later.
- Support for authentication (needs some extra logic) will be done in a follow-up PR.
> Add support for MSW

- .devcontainer/Dockerfile
- The base docker image for the devcontainer was not pinned to an exact version, which means developers could end up using node 22.9 or node 22.12 depending on the time they built the devcontainer image.
- node 22.12 introduced the experimental require(esm) feature which throws an error when the http proxy middleware loads the configuration from proxy.conf.js.
- This PR pins the devcontainer base image to version 1.1.8 which uses node 22.12.
- Therefore this PR also explicitly disables the require(esm) feature using the `NODE_OPTIONS` env var.
- This PR also includes minor updates to pnpm and Angular.
> Pin devcontainer base and fix issue with Node 22.12

- src/app/auth/services/auth.service.ts
Since the login process includes redirections and reloading of the page, we need to memorize the original page before login in the session storage.
> Memorize location before login in session storage

- .devcontainer/create_cert
- .devcontainer/dev_launcher
- README.md
- proxy.conf.js
- run.js
- src/app/shared/services/config.service.ts
- src/main.ts
- src/mocks/handlers.ts
- src/mocks/responses.ts
This PR makes the `run.js` script a bit more flexible. Besides running the production server, it can now run the dev server in four different modes:
- with mock API and fake authentication
- with real backend, but fake authentication
- with real OIDC provider, but mock backend
- with real backend and OIDC provider
The dev server is activated by passing the `--dev` option. The `dev_launcher` script calls the `run.js` script with this option, while passing on any other options.
See also the update documentation in the README file.
> Support more modes for running the dev server (GSI-1233)

- proxy.conf.js
- run.js
If running without backend and fake OIDC, set base URL to localhost even if configurated differently.
Only show the hint to open the browser with the staging URL when needed.
> Do not use staging URL if not needed

- proxy.conf.mjs
- src/app/auth/services/auth.service.ts
- src/app/metadata/features/dataset-expansion-panel/dataset-expansion-panel.component.ts
- src/app/metadata/features/metadata-browser/metadata-browser.component.ts
- src/mocks/auth.ts
- src/mocks/handlers.ts
- fix registration URL in mock service
- memorize the authentication state in mock service
- ignore HMR URLs when mocking the API
- end snackbar messages with a period
We try to keep the mock service backend simple and stateless, but for testing it makes sense to preserve the authentication state in session storage.
> Fix and improve auth process with mock service

- .devcontainer/data-portal.yaml
- data-portal.default.yaml
- jest.config.ts
- src/app/shared/services/config.service.spec.ts
- src/app/shared/services/config.service.ts
- src/app/work-packages/models/dataset.ts
- src/app/work-packages/models/workPackage.ts
- src/app/work-packages/services/work-package.service.spec.ts
- src/app/work-packages/services/work-package.service.ts
This PR adds the Angular service with the two methods needed to interact with the work package service on the backend:
- find all datasets for which work packages can be created
- create a work package
The first one is usable via three corresponding signals, but I kept the return value of the second one as an observable, so you need to subscribe. A resource does not seem to be the right paradigm here, and converting to a promise or signal doesn't look very appealing either. So I suggest we stick to observables for mutations.
The PR also shows how we can simplify the code using an rxResource, and how to test it. This is a bit tricky - you need to use the new and hardly known flushEffects if the service is not running in the context of a component. Also, waiting for a tick was needed to get …
> Add work package service

- eslint.config.js
- src/app/access-requests/features/access-request-dialog/access-request-dialog.component.html
- src/app/access-requests/features/access-request-dialog/access-request-dialog.component.ts
- src/app/access-requests/features/access-request-manager-dialog/access-request-manager-dialog.component.html
- src/app/access-requests/features/access-request-manager-dialog/access-request-manager-dialog.component.ts
- src/app/access-requests/features/access-request-manager-filter/access-request-manager-filter.component.html
- src/app/access-requests/features/access-request-manager-filter/access-request-manager-filter.component.ts
- src/app/access-requests/features/access-request-manager-list/access-request-manager-list.component.html
- src/app/access-requests/features/access-request-manager-list/access-request-manager-list.component.ts
- src/app/access-requests/features/granted-access-requests-list/granted-access-requests-list.component.html
- src/app/access-requests/features/granted-access-requests-list/granted-access-requests-list.component.ts
- src/app/access-requests/features/pending-access-requests-list/pending-access-requests-list.component.html
- src/app/access-requests/features/pending-access-requests-list/pending-access-requests-list.component.ts
- src/app/app.config.ts
- src/app/shared/utils/date-formats.ts
- src/app/verification-addresses/features/iva-manager-filter/iva-manager-filter.component.html
- src/app/verification-addresses/features/iva-manager-filter/iva-manager-filter.component.ts
- src/app/verification-addresses/features/iva-manager-list/iva-manager-list.component.html
- src/app/verification-addresses/features/iva-manager-list/iva-manager-list.component.ts
- Move all date format definitions used in the application to shared/utils/date-formats
- Use these formats in app.config.ts to configure the DateFnsAdapter and the standard DatePipe
- Use the default date format for tabular output, and shortDate format for dates that are part of prose
- Show the defined input date format as hint for date picker input fields
> Centralize date format (GSI-1424)

- package.json
- src/app/access-requests/features/dynamic-access-request-button/dynamic-access-request-button.component.spec.ts
- src/app/auth/features/register/register.component.spec.ts
- src/app/auth/models/user.ts
- src/app/auth/services/auth.service.ts
- src/app/metadata/features/dataset-details/dataset-details.component.spec.ts
- src/app/metadata/features/dataset-summary/dataset-summary.component.spec.ts
- src/app/metadata/features/search-result/search-result.component.spec.ts
- src/app/portal/features/account-button/account-button.component.html
- src/app/portal/features/account-button/account-button.component.spec.ts
- src/app/portal/features/account-button/account-button.component.ts
- src/app/portal/features/account/account.component.html
- src/app/portal/features/account/account.component.spec.ts
- src/app/portal/features/account/account.component.ts
- src/app/portal/features/admin-menu/admin-menu.component.spec.ts
- src/app/portal/features/admin-menu/admin-menu.component.ts
- src/app/shared/utils/errors.ts
- src/mocks/auth.ts
This PR adds support for the new session object of Auth Service v3 which can have multiple roles.
The old version is still supported for now.
The PR also bumps the version number to 2.0.0-rc1.
> Support Auth Service v3 with multi role support (GSI-1495)

- src/app/shared/services/umami.service.ts
- src/mocks/handlers.ts
- src/mocks/umami.ts
This PR addresses the following issues:
1. allow disabling Umami via configuration
2. make Umami work with client side navigation
3. mock Umami with MSW (just log what is tracked)
To solve 2. I used the following approach:
- disable the auto-tracking on the script tag (this disables pageview tracking, but sadly also event tracking)
- manually track the client side navigation
- manually track events similar to how Umami would do it with auto-tracking
> Improve the Umami integration

- package.json
- pnpm-lock.yaml
- src/app/access-requests/features/access-request-dialog/access-request-dialog.component.html
- src/app/access-requests/features/access-request-dialog/access-request-dialog.component.spec.ts
- src/app/access-requests/features/access-request-dialog/access-request-dialog.component.ts
- src/app/access-requests/features/access-request-manager-dialog/access-request-manager-dialog.component.html
- src/app/access-requests/features/access-request-manager-dialog/access-request-manager-dialog.component.spec.ts
- src/app/access-requests/features/access-request-manager-dialog/access-request-manager-dialog.component.ts
- src/app/access-requests/services/access-request.service.ts
- src/app/verification-addresses/features/code-creation-dialog/code-creation-dialog.component.html
- src/app/verification-addresses/features/iva-manager-filter/iva-manager-filter.component.ts
- src/app/verification-addresses/features/iva-manager-list/iva-manager-list.component.html
- src/app/verification-addresses/features/iva-manager-list/iva-manager-list.component.ts
- src/app/verification-addresses/features/new-iva-dialog/new-iva-dialog.component.ts
- src/app/verification-addresses/features/user-iva-list/user-iva-list.component.html
- src/app/verification-addresses/features/user-iva-list/user-iva-list.component.ts
- src/app/verification-addresses/pipes/iva-state.pipe.spec.ts
- src/app/verification-addresses/pipes/iva-state.pipe.ts
- src/app/verification-addresses/pipes/iva-type.pipe.spec.ts
- src/app/verification-addresses/pipes/iva-type.pipe.ts
- src/mocks/data.ts
- src/mocks/responses.ts
This PR fixes some more bugs that have been found when testing rc.2 against the staging backend:
- The IVA types and values were not shown properly. This was caused by several problems with the implementation of the IvaTypePipe and IvaStatusPipe.
- The access requests were not properly sent to the backend; some fields were missing or in the wrong format.
- Also, some controls used both template driven and reactive form controls, causing a warning on the console.
- When there was an error on the backend, like due to the above, the success message was shown anyway.
- The IVA id was not submitted when allowing/denying requests. The cause was a signal that was not called.
- The backend does not allow reverting a status of "denied" to "allowed", so the frontend shouldn't offer that option …
> Fix bugs in rc.2

- .husky/pre-commit
Do not allow commits to the main branch directly. This is disabled on GitHub anyway, but it's better to catch this already on the local repository as well.
> Prevent commits to main branch

- package.json
- src/app/metadata/features/metadata-browser/metadata-browser.component.html
- src/app/metadata/features/metadata-browser/metadata-browser.component.ts
- src/mocks/data.ts
In the legacy portal, we only showed facets with less than 6 options. This PR re-implements the feature in the new portal.
> Skip facets with many items (GSI-1591)

- package.json
- src/app/metadata/features/global-summary/global-summary.component.html
- src/app/metadata/features/global-summary/global-summary.component.spec.ts
- src/app/metadata/features/global-summary/global-summary.component.ts
- src/app/metadata/features/metadata-browser/metadata-browser.component.ts
- tests/home.spec.ts
The global stats currently shows the number of experiments instead of the number of different platforms as before.
We decided to fix that by changing the label to "experiments" instead of "platforms".
This PR also fixes the problem that empty facets resulted in headings with now option by skipping these facets.
> Fix global stats platform/experiment

- src/app/metadata/features/dataset-details/dataset-details.component.html
The View Publication button used to direct users to https://data.ghga.de/DOI instead of https://doi.org/DOI
> Fixing the host of the link of the View Publication button

- Dockerfile
- run.js
- sws.toml
Unlike JS and CSS bundles, which Angular are built with hash values as file names,, the index file is fixed. If browsers cache it, users may continue to load an old version, which references outdated bundles that no longer exist after a deployment. This can result in broken pages or missing resources.
The PR fixes this by adding a config file to SWS that adds no-cache headers to the index file (and only to that file).
> Disallow caching of index page (GSI-1659)

- src/app/auth/features/confirm-totp/confirm-totp.component.html
- src/app/auth/features/confirm-totp/confirm-totp.component.ts
When submitting a 2FA code, it was checked twice against the backend, because the onSubmit method was called on both the form and the submit button.
This PR removes the call on the button and makes sure that a new submission is not possible while the check is still running (e.g. when double clicking the button).
> Fix duplicate 2FA verification (GSI-1676)

- src/app/metadata/features/dataset-details/dataset-details.component.html
- src/app/metadata/features/dataset-summary/dataset-summary.component.html
- src/app/shared/ui/summary-badges/summary-badges.component.html
- src/app/shared/ui/summary-badges/summary-badges.component.spec.ts
- src/app/shared/ui/summary-badges/summary-badges.component.ts
In dataset summary:
If there are 4 elements (or more), it should show a `Show 2 more` link.
If there are only 3 elements or fewer, it should show them all. Added a test for these edge cases.
Fixed class names for some mat-chips.
> Show more shows from 4 elements in summary (GSI-1668)

- src/app/access-requests/features/access-request-field-edit/access-request-field-edit.component.ts
- It was not possible to clear fields of access requests when they already had a value.
- Ticket link was shown even when there was no ticket ID.
> Allow clearing fields of access requests

- src/app/shared/pipes/date.pipe.spec.ts
- src/app/shared/pipes/date.pipe.ts
The DatePipe that is shipped with Angular does not support IANA time zones, only fixed zone offsets. We need dynamic zones for the access and end dates. Therefore, I added an improved date pipe that supports the dynamic IANA zones.
> Add date pipe that supports IANA time zone names

- src/app/access-requests/features/access-request-dialog/access-request-dialog.component.ts
- src/app/access-requests/features/access-request-duration-edit/access-request-duration-edit.component.html
- src/app/access-requests/features/access-request-duration-edit/access-request-duration-edit.component.ts
- src/app/access-requests/features/access-request-manager-list/access-request-manager-list.component.html
- src/app/access-requests/features/access-request-manager-list/access-request-manager-list.component.ts
- src/app/shared/pipes/date.pipe.ts
- src/app/shared/utils/date-formats.spec.ts
- src/app/shared/utils/date-formats.ts
The access period should be converted from German time zone to UTC when stored and vice versa when displayed.
> Improve time zone handling for access periods

- src/app/access-requests/features/access-request-manager-dialog/access-request-manager-dialog.component.ts
- src/app/app.routes.ts
- src/app/auth/features/register/register.component.spec.ts
- src/app/auth/features/user-manager-detail/user-manager-detail.component.html
- src/app/auth/features/user-manager-detail/user-manager-detail.component.scss
- src/app/auth/features/user-manager-detail/user-manager-detail.component.spec.ts
- src/app/auth/features/user-manager-detail/user-manager-detail.component.ts
- src/app/auth/features/user-manager-list/user-manager-list.component.html
- src/app/auth/features/user-manager-list/user-manager-list.component.scss
- src/app/auth/features/user-manager-list/user-manager-list.component.spec.ts
- src/app/auth/features/user-manager-list/user-manager-list.component.ts
- src/app/auth/features/user-manager/user-manager.component.html
- src/app/auth/features/user-manager/user-manager.component.spec.ts
- src/app/auth/features/user-manager/user-manager.component.ts
- src/app/auth/models/user.ts
- src/app/auth/pipes/user-status-class.pipe.spec.ts
- src/app/auth/pipes/user-status-class.pipe.ts
- src/app/auth/services/auth.service.ts
- src/app/auth/services/user.service.spec.ts
- src/app/auth/services/user.service.ts
- src/app/portal/features/account-button/account-button.component.spec.ts
- src/app/portal/features/admin-menu/admin-menu.component.html
- src/app/portal/features/admin-menu/admin-menu.component.ts
- src/mocks/auth.ts
- src/mocks/data.ts
- src/mocks/responses.ts
This PR implements the main list view for the user management page.
It already includes a stub for the detail page and the navigation between the two.
The corresponding view transition will be implemented in a separate PR since it turned out to be not so easy as anticipated.
The filter section will also be implemented in a separate PR.
> Add user management list view (GSI-1734)

- eslint.config.js
All other a11y rules already enabled
Made it so ESLint also checks inline templates (if any)
> Added missing tabindex rule to ESLint

- .github/workflows/e2e.yml
This PR makes the GitHub e2e tests run not just on Chromium (Blink), but also on Firefox (Gecko) and Webkit (Safari).
It also adds a bit of caching and other small optimizations to speed up and stabilize the tests.
> Improve the e2e testing with GitHub
